version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - flask_net
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""

  flask_app:
    build: .
    container_name: flask_container
    networks:
      - flask_net
    ports:
      - "8080:5000"

networks:
  flask_net:
    driver: bridge

volumes:
  mysql_data:
