"""add filesupload

Revision ID: 2a2142d11156
Revises: 
Create Date: 2024-01-13 12:09:01.727470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2142d11156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=256), nullable=False),
    sa.Column('lastname', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('profile_picture', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('market_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=140), nullable=False),
    sa.Column('company_name', sa.String(length=140), nullable=False),
    sa.Column('price', sa.String(length=140), nullable=False),
    sa.Column('net_change', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_request_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_request_user_id'), ['user_id'], unique=False)

    op.create_table('upload_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('upload_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_file_upload_at'), ['upload_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_file_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_file_user_id'))
        batch_op.drop_index(batch_op.f('ix_upload_file_upload_at'))

    op.drop_table('upload_file')
    with op.batch_alter_table('market_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_market_request_timestamp'))

    op.drop_table('market_request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
